<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Query</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach($queries as $query)
        <tr>
            <td>{{$query->name}}</td>
            <td>{{$query->descripton}}</td>
            <td>{{$query->queryText()}}</td>
            <td></td>
        </tr>
    @endforeach
    </tbody>
</table>